### ISSUE TITLE
Error Contents: HTTP Error 308: Permanent Redirect

### ISSUE THREAD

**Issue by Washee** [christianprasch/plugin.video.tagesschau#2]
Hi,

I am running the version 2.2.2 of this plugin on a raspberry pi 3 running LibreElec.

I get the following error, when I start the app.
I am not sure, but it looks like the resource of the tagesschau api moved ? Or something similar.

If I am wrong and this problem is related to my general setup, I apologize for bothering you with this.
But I am very clueless how to fix this at the moment.

> 2022-03-22 20:03:47.347 T:1937133632   ERROR: Control 500 in window 10025 has been asked to focus, but it can't
2022-03-22 20:03:47.637 T:1522705280   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 308: Permanent Redirect
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.tagesschau/tagesschau.py", line 157, in <module>
                                                videos = provider.livestreams()
                                              File "/storage/.kodi/addons/plugin.video.tagesschau/tagesschau_json_api.py", line 269, in livestreams
                                                data = self._jsonsource.livestreams()
                                              File "/storage/.kodi/addons/plugin.video.tagesschau/tagesschau_json_api.py", line 360, in livestreams
                                                handle = urllib2.urlopen("http://www.tagesschau.de/api/multimedia/video/ondemand100~_type-video.json")
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 308: Permanent Redirect
                                            -->End of Python script error report<--
2022-03-22 20:03:47.830 T:1807721344   ERROR: GetDirectory - Error getting plugin://plugin.video.tagesschau/
2022-03-22 20:03:47.839 T:1937133632   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.tagesschau/) failed

**Comment by Josef-Friedrich** [comment]
The same for me

**Comment by Patschke** [comment]
Same error occurs for me. The permanent redirect seems to point to the `https` version of that site. 

It seems like tageschau.de no longer supports http queries but enforces https (and attempts to redirect to that). Editing `tagesschau_json_api.py` (for me in `~/.kodi/addons/plugin.video.tagesschau/tagesschau_json_api.py`) resolved those issues: 

```diff
diff --git a/libs/tagesschau_json_api.py b/libs/tagesschau_json_api.py
index 32aa8f4..962d2ae 100644
--- a/libs/tagesschau_json_api.py
+++ b/libs/tagesschau_json_api.py
@@ -142,7 +141,16 @@ class LazyVideoContent(VideoContent):
     def _fetch_details(self):
         """Fetches videourls from detailsurl."""
         self._logger.info("fetching details from " + self.detailsurl)
-        handle = urllib.request.urlopen(self.detailsurl)
+        try:
+            handle = urllib2.urlopen(self.detailsurl)
+        except urllib2.HTTPError as e:
+            # check if we need to switch to https.
+            if self.detailsurl.startswith("http:"):
+                self._logger.info("failed. try with https instead")
+                handle = urllib2.urlopen("https:" + self.detailsurl[5:])
+            else:
+                # whatever. Let somebody else handle that (in fact nobody will - kodi will just show an error)
+                raise e
         jsondetails = json.load(handle)
         self._videourls = self._parser.parse_video_urls(jsondetails["fullvideo"][0]["mediadata"])
         self._videoid = jsondetails["fullvideo"][0]["sophoraId"]
@@ -358,26 +366,55 @@ class JsonSource(object):

     def livestreams(self):
         """Returns the parsed JSON structure for livestreams."""
-        handle = urllib2.urlopen("http://www.tagesschau.de/api/multimedia/video/ondemand100~_type-video.json")
+        handle = urllib2.urlopen("https://www.tagesschau.de/api/multimedia/video/ondemand100~_type-video.json")
         return json.loads(handle.read())

     def latest_videos(self):
         """Returns the parsed JSON structure for the latest videos."""
-        handle = urllib2.urlopen("http://www.tagesschau.de/api/multimedia/video/ondemand100~_type-video.json")
+        handle = urllib2.urlopen("https://www.tagesschau.de/api/multimedia/video/ondemand100~_type-video.json")
         return json.loads(handle.read())

     def dossiers(self):
         """Returns the parsed JSON structure for the dossiers."""
-        handle = urllib2.urlopen("http://www.tagesschau.de/api/multimedia/video/ondemanddossier100.json")
+        handle = urllib2.urlopen("https://www.tagesschau.de/api/multimedia/video/ondemanddossier100.json")
         return json.loads(handle.read())

     def latest_broadcasts(self):
         """Returns the parsed JSON structure for the latest broadcasts."""
-        handle = urllib2.urlopen("http://www.tagesschau.de/api/multimedia/sendung/letztesendungen100.json")
+        handle = urllib2.urlopen("https://www.tagesschau.de/api/multimedia/sendung/letztesendungen100.json")
         return json.loads(handle.read())

     def archived_broadcasts(self):
         """Returns the parsed JSON structure for the archived broadcasts."""
-        handle = urllib2.urlopen("http://www.tagesschau.de/api/multimedia/sendung/letztesendungen100~_week-true.json")
+        handle = urllib2.urlopen("https://www.tagesschau.de/api/multimedia/sendung/letztesendungen100~_week-true.json")
         return json.loads(handle.read())
```

I ended up in this repo when googling for the error message. However, the git diff between the version in this repo and the version installed in Kodi suggests, that it is not the upstream repository. I have to admit that I am currently too lazy to search for the correct upstream and submit a PR...

Edit: For those who stumble accros this thread and want to fix it themself right now: Just edit the file with any editor of your choice as shown above and restart kodi. I did no in depth testing (the same error may very well occur on other stuff), but viewing the latest broadcast worked for me and that's all I care about.

**Comment by beta-tester** [comment]
hi i have also this issues (at least since the last two days) with Tagesschau add-on on my
- RPi3 + official LibreELEC 9.2 (Kodi Leia) + Tagesschau Add-On 2.2.2

and i tried
- RPi3 + official LibreELEC 10.0.2 (Kodi Matrix) + Tagesschau Add-On 2.3.0

both installations showing the same issue.

**Comment by beta-tester** [comment]
@Josef-Friedrich & @Patschke:
changing `http` to `https` fixed it.
thank you for the hints

@christianprasch:
while editing the file with `nano` it highlighted a lot of empty spaces at line endings

**Comment by Josef-Friedrich** [comment]
I’m still on Kodi 18: Here is my patched version for Kodi 18: https://github.com/Josef-Friedrich/kodi18.plugin.video.tagesschau

**Comment by rfuh** [comment]
~~shouldn't the fix be as simple as replacing http by https in [tagesschau_json_api.py](https://github.com/christianprasch/plugin.video.tagesschau/blob/master/libs/tagesschau_json_api.py#L355)?~~
Just noted the PR is already there 😄 Thanks!

**Comment by Patschke** [comment]
> ~shouldn't the fix be as simple as replacing http by https in [tagesschau_json_api.py](https://github.com/christianprasch/plugin.video.tagesschau/blob/master/libs/tagesschau_json_api.py#L355)?~ Just noted the PR is already there smile Thanks!

For me that wasn't enough - since e. g. the `details` url provided in the json file served at http://www.tagesschau.de/api/multimedia/video/ondemand100~_type-video.json does contain `http` instead of `https`. So I needed to catch that and dynamically replace it with `https`...

**Comment by rfuh** [comment]
As Tagesschau actually provides the redirect information in the Location header with return code 308, would probably something like this in `_fetch_details()` be more generic?
```
        try:
            handle = urllib.urlopen(self.detailsurl)
        except urllib.HTTPError as e:
            if (e.code >= 300 and e.code < 400):
                handle = urllib.urlopen(e.headers['Location'])
```

**Comment by christianprasch** [comment]
I have now pushed a new version implementing the changes from Josef. Thanks for this Josef.
There was one thing not working: latest broadcasts. For this to work again i changed urllib.urlopen to urllib.request.urlopen and urllib.HTTPError to urllib.error.HTTPError in tagesschau_json_api.py:

old:
```
        try:
            handle = urllib.urlopen(self.detailsurl)
        except urllib.HTTPError as e:
            # check if we need to switch to https.
            if self.detailsurl.startswith("http:"):
                self._logger.info("failed. try with https instead")
                handle = urllib.urlopen("https:" + self.detailsurl[5:])
```

changed:
```
        try:
            handle = urllib.request.urlopen(self.detailsurl)
        except urllib.error.HTTPError as e:
            # check if we need to switch to https.
            if self.detailsurl.startswith("http:"):
                self._logger.info("failed. try with https instead")
                handle = urllib.request.urlopen("https:" + self.detailsurl[5:])
```

Since i am no experienced python developer i would appreciate any feedback if this changes work for you.
If i get positive feedback (or in a few days if not) i will PR this to the Kodi team.

**Comment by christianprasch** [comment]
Using now the code fragment from rfhu. Seems to be the proper way to handle the redirect. Thanks for that!

**Comment by beta-tester** [comment]
is this add-on only for Kodi Matrix or can i use it for Kodi Leia as well?

**Comment by christianprasch** [comment]
Leia uses older Python version. So Addons for Matrix will not run on Leia.
