### ISSUE TITLE
"HTTP" not working anymore, maybe "HTTPS" does the trick?

### ISSUE THREAD

**Issue by TimZiemer** [christianprasch/plugin.video.tagesschau#5]
Hi there,
Unfortunately, the PlugIn is not working anymore.

According to Kodinerds replacing "http" to "https" in tagesschau.py, tagesschau_json_api.py and tagesschau_json_api.pyo only helped to fix "Tagesschau in 100 Sekunden" but not Tagesschau and other broadcasts:
https://www.kodinerds.net/index.php/Thread/74867-Tagesschau-weg/?postID=685773&highlight=tagesschau#post685773

Best,
Tim

**Comment by christianprasch** [comment]
Hi Tim,

are you using the latest version 2.3.2? I can not reproduce any malfunction here.

Regards,
Christian

**Comment by TimZiemer** [comment]
Hi Christian,

I was using the latest version that was available for Kodi 18.3. and it only worked after I manually followed the instructions on:
https://www.kodinerds.net/index.php/Thread/74867-Tagesschau-weg/?postID=686069&highlight=tagesschau#post686069

Best,
Tim
