### ISSUE TITLE
addon broken

### ISSUE THREAD

**Issue by beta-tester** [christianprasch/plugin.video.tagesschau#6]
the addon is broken since few days.
maybe the link changed.

the old web link was:
https://www.tagesschau.de/multimedia/tagesschau_20_uhr/

now the new link is:
https://www.tagesschau.de/multimedia/sendung/tagesschau_20_uhr/

maybe something in the api changed as well.
https://github.com/bundesAPI/tagesschau-api
https://tagesschau.api.bund.dev/
https://bund.dev/apis/

**Comment by vitusson** [comment]
> maybe something in the api changed as well.

Seems so. Or somebody at ARD broke something
https://github.com/AndreasFischer1985/tagesschau-api/issues/12

**Comment by christianprasch** [comment]
ARD has now disabled the old API.
I am uploading a new version right now and do a PR to the kodi team.

**Comment by beta-tester** [comment]
> I am uploading a new version right now and do a PR to the kodi team.

thank you very much.

will this update be available for Kodi 19 (Matrix) as well or only for the newest Kodi 20 (Nexus)?

**Comment by christianprasch** [comment]
The addon is available for 19 and 20

**Comment by beta-tester** [comment]
the new addon is online now.
unfortunately i can not see any "Tagesschau 20Uhr" from the last few days. only the most recent i can see.
in the past i could see more than one "Tagesschau 20Uhr" entries from different days.
i guess it is because of the API endpoint "[multimedia](https://www.tagesschau.de/api2/multimedia/)" is gone.

**Comment by christianprasch** [comment]
I use https://www.tagesschau.de/api2u/news for the "Nachrichten" listing and https://www.tagesschau.de/api2u/channels for the "Sendungen" listing.
The news page does not list 20:00 tagesschau and the channels page only lists the latest broadcast.

I am also not amused about this change. If you have an idea how to get more info i would be glad to get suggestions.

**Comment by beta-tester** [comment]
i noticed that the search API endpoint is restored/migrated again to the new API2.
e.g.: https://www.tagesschau.de/api2u/search/?searchText=Tagesschau+20+Uhr
i get a JSON list of 'Tagewsschau' entries
but they must be filtered by `date` to take only entries for 20:00, because the search result includes items from other day times.

search with:
https://www.tagesschau.de/api2u/search/?searchText=Tagesschau+Geb%C3%A4rdensprache
gives just 'Tagesschau 20 Uhr' items
(ok it is with 'Gebärdensprache' but that does not hurt that much if you just want to get the news content of the past few days and don't care about the size of the pictures they show)

'Tagesthemen' is also of interest to me:
https://www.tagesschau.de/api2u/search/?searchText=Tagesthemen

**Comment by christianprasch** [comment]
I have now added a listing for the 20:00 tagesschau as suggested by you. I filtered so that only videos with a length between 890-910 s are used, this results in only 20:00 broadcasts.
Also added a listing for tagesthemen. There the individual news from tagesthemen are listed as well as the complete broadcast (simply the result for a search to tagesthemen).
Since i have an open PR for my weltspiegel pluging i will delay the PR for this tagesschau update to the Kodi team.
But you can use the version from my repo.
Thanks for your support in this issue!

**Comment by beta-tester** [comment]
i just tested the new version with 'Tagesschau 20 Uhr' and 'Tagesthemen'

'Tagesschau 20 Uhr' is perfect !

'Tagesthemen' i get the full 'Tagesthemen' shows of the day, with all the topics of the day in one show, and the same show in small parts divided by topic. maybe it would be good to add a filter by length as well.

PS.: i also installed you 'Weltspiegel' addon - also nice.

**Comment by christianprasch** [comment]
Pushed a new version: in the addon settings there is an option to choose what to show in the tagesthemen listing: broadcasts only, topics only or both.

**Comment by beta-tester** [comment]
version `2.5.1` is not working on Kodi Matrix (LibreELEC release: RPi2.arm-10.0.4, Raspberry Pi 3B+).
it gives an error that i have to look to the log file, but where is the addons logfile?

```log
2023-05-09 22:16:32.989 T:759     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndentationError'>
                                                   Error Contents: expected an indented block (tagesschau_json_api.py, line 301)
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.tagesschau/main.py", line 19, in <module>
                                                       from libs.tagesschau import tagesschau
                                                     File "/storage/.kodi/addons/plugin.video.tagesschau/libs/tagesschau.py", line 23, in <module>
                                                       from libs.tagesschau_json_api import VideoContentProvider, JsonSource, addon
                                                     File "/storage/.kodi/addons/plugin.video.tagesschau/libs/tagesschau_json_api.py", line 301
                                                       videos.append(video)
                                                       ^
                                                   IndentationError: expected an indented block
                                                   -->End of Python script error report<--
                                                   
```

the addon is working well, when adding indentation to line 301 of `libs/tagesschau_json_api.py`

PS.: while editing the file with the editor `nano`, the editor highlighted me few blanks just before line endings.

**Comment by beta-tester** [comment]
there is another ERROR, when selecting the option Sendungen`

```log
2023-05-09 23:29:29.471 T:906     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'title'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.tagesschau/main.py", line 22, in <module>
                                                       tagesschau()
                                                     File "/storage/.kodi/addons/plugin.video.tagesschau/libs/tagesschau.py", line 160, in tagesschau
                                                       videos = videos_method()
                                                     File "/storage/.kodi/addons/plugin.video.tagesschau/libs/tagesschau_json_api.py", line 255, in latest_broadcasts
                                                       video = self._parser.parse_broadcast(jsonbroadcast)
                                                     File "/storage/.kodi/addons/plugin.video.tagesschau/libs/tagesschau_json_api.py", line 159, in parse_broadcast
                                                       title = jsonbroadcast["title"]
                                                   KeyError: 'title'
                                                   -->End of Python script error report<--
```

**Comment by christianprasch** [comment]
Sorry for the indent error, is fixed now.
I can not reproduce the KeyError. But it looks like there was an video entry without title information in the json data. I have added a check for this.

**Comment by beta-tester** [comment]
> I can not reproduce the KeyError

i just tried it again with the old version 2.5.1 but i can't reproduce that error anymore. strange. could be a temporary problem.

> Sorry for the indent error, is fixed now.
> ... I have added a check for this.

thank you very much for the new version. i think now it is perfect.

**Comment by beta-tester** [comment]
there is again something odd.
this time the 'Tagesschau 20 uhr' option throes an exception:

```log
2023-05-22 23:00:29.101 T:1429    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'length'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.tagesschau/main.py", line 22, in <module>
                                                       tagesschau()
                                                     File "/storage/.kodi/addons/plugin.video.tagesschau/libs/tagesschau.py", line 160, in tagesschau
                                                       videos = videos_method()
                                                     File "/storage/.kodi/addons/plugin.video.tagesschau/libs/tagesschau_json_api.py", line 272, in tagesschau_20
                                                       length = int(jsonvideo["tracking"][1]["length"])
                                                   KeyError: 'length'
                                                   -->End of Python script error report<--
```

**Comment by christianprasch** [comment]
There was a video entry in the search result list without the expected "length" attribute. Now all results with expected but missing attributes are ignored.
