### ISSUE TITLE
Inhaltstyp Video

### ISSUE THREAD

**Issue by C-O-D** [christianprasch/plugin.video.tagesschau#7]
Hallo, könntest du bitte den Inhaltstyp für die Nachrichten und die Tagesthemen auf Video setzen?
Ich benutze das neue Skin Arctic Fuse und bekomme dort nicht die Möglichkeit, den Ansichtstyp Landscape auszuwählen weil wohl der Inhaltstyp nicht richtig auf Video gesetzt ist - sagt der Entwickler.
Desweiteren habe ich auch in anderen Skins, bei denen das komischerweise funktioniert das Problem, dass bei den Tagesthemen die Landscape Thumbs immer nur das Fanart angezeigen und nicht die Preview wie bei den Nachrichten - kannst du da was machen?

Vielen Dank und viele Grüße

**Comment by christianprasch** [comment]
Leider konnte ich bisher keine Lösung für das Landscape-Problem finden. Der Inhaltstyp ist bereits Video.
Ich habe jetzt mal auf der Github-Seite der Skin nachgefragt. Sobald ich was weiß melde ich mich.

Viele Grüße
Christian

**Comment by christianprasch** [comment]
Mit hilfe von jurialmunkey konnte ich die fehlenden Angaben jetzt ergänzen, bei mir funktioniert es. Auch die Preview bei den Tagesthemen funktioniert jetzt.
Zusätzlich gibt es jetzt zwei neue Optionen in den Einstellungen um die nervigen "Europadruck" und "Aktueller Wolkenfilm" Einträge bei den Nachrichten zu unterdrücken. Beide Optionen sind per Default aktiv.
Ich stelle einen PullRequest an das Kodi Team.

Viele Grüße
Christian

**Comment by C-O-D** [comment]
Klasse, ich bin begeistert - vielen vielen Dank und viele Grüße!

**Comment by C-O-D** [comment]
Hallo Christian,
in der neuen Version sind jetzt die Kategorie Thumbnails (landscape) leer, also ohne Bild. Könntest du vielleicht für die Kategorie Seite den Inhalt NICHT definieren, dann hätte man z.b beim skin Arctic Fuse dort die quadratische Ansicht zur Auswahl bei der dann das Icon von Add-On erscheinen müsste während das fanart im Hintergrund erscheint. So wär's glaube ich richtiger und vielleicht auch schöner (beim TIDAL2 Add-On wurde das bspw. so gemacht).
Und noch eine Sache, die hiermit nichts zu tun hat - könntest du eventuell die Auflösung 1920 x 1080 zur Verfügung stellen? Die Auflösung scheint ja prinzipiell vorhanden zu sein, da sie im Add-On ARDundZDF für dieselben Beiträge auch verfügbar ist...

Viele Grüße

**Comment by christianprasch** [comment]
Jetzt musst du mir etwas helfen:
Mit Kategorie-Seite meinst du die Auswahl Nachrichten/Sendungen/... oder?
Bei mir sind da bei jeder Kategorie die blauen Tagesschau-Bilder (also das Addon Icon) und im Hintergrund Judith Rakers.
Was möchtest du da anders?
Bei den weiteren Listen sind die Bilder von der ARD-Seite in der Auflösung 640 verwendet was für die kleinen Bilder reichen sollte. Sollen diese Bilder auch als Fanart angezeigt werden? Dann bräuchte es natürlich die 1080er.

**Comment by christianprasch** [comment]
Ich habe jetzt mal die Vorschaubilder in der 1920er Auflösung als Fanart eingebunden. Ist eine Option in den Einstellungen, per default aktiv. Lade dir mal den Code von meiner Github-Seite als zip und installiere es.
Möchte eigentlich erst einen PullRequest aufmachen wenn alles wie gewünscht ist.

**Comment by C-O-D** [comment]
Hey, die Vorschaubilder optional als Fanart anzuzeigen ist eine gute Idee, kannst du wegen mir sehr gerne drin lassen (sehr hilfreich für die Widget Anzeige) - aber das meinte ich eigentlich nicht. Die Auflösung bezog ich auf die Videos selbst, ob du diese nicht in Full HD verfügbar machen kannst.

> Mit Kategorie-Seite meinst du die Auswahl Nachrichten/Sendungen/... oder?

Ja genau, und die entsprechenden Thumbnails (landscape) zeigen bei mir nichts an. Ich habe kürzlich auch meine thumbnails bereinigt und diese wurden nicht neu aufgebaut, das heißt, wenn sie bei dir noch angezeigt werden liegt es vielleicht daran dass du sie noch im Thumbnail Cache hast.
Und wie gesagt, ich fänd's cool wenn diese Bilder quadratisch sein könnten, was bei dem Skin Arctic Fuse (und auch anderen skins von jurialmunkey) wohl nur geht, wenn der Inhalt dieser Seite, die ja das Auswahlmenü darstellt, nicht als 'videos' deklariert ist sondern gar nichts oder 'file' oder so. Also zusammengefasst, die Menü/Kategorie-Seite sollte quadratische Icons haben mit dem Tagesschau Icon und die entsprechenden Unterseiten dann landscape, so wie es jetzt bereits schon ist.

Viele Grüße

**Comment by christianprasch** [comment]
Das mit den Vorschaubildern sollte jetzt gefixed sein. Die kamen bisher direkt von der ARD-Webseite. Der Link funktioniert aber nicht mehr. Ich verwende jetzt hinterlegte Bilder im AddOn.
Größere Videoauflösungen kann ich momentan leider nicht anbieten. Das AddOn verwendet die Tagesschau-API, nicht die Mediathek. Und in der Tagesschau-API gibt es maximal 720er Videos.
Bitte teste mal die Version die ich gerade gepusht habe und gib mir Feedback.
Gruß Christian

**Comment by C-O-D** [comment]
Alles perfekt jetzt, hab' vielen Dank Christian!
