### ISSUE TITLE
Live Stream

### ISSUE THREAD

**Issue by eusi** [christianprasch/plugin.video.tagesschau#8]
Hallo,
bin ich blind oder gibt es den Live Stream nicht mehr? Ich war mir sicher, dass das Addon neben "Nachrichten", "Tagesthemen 20 Uhr" etc. auch "Tagesthemen Live" (o.ä. Wortlaut) hatte?

Beispiel: Es ist 19:55 und ich möchte nun gleich die Tagesschau "live" sehen, also klicke ich auf den Reiter für "Live".

Schöne Grüße
eusi

**Comment by christianprasch** [comment]
Hallo eusi,

den Livestream gibt es schon. Bei Aufruf des Hauptliste prüft das Plugin ob
ein Livestream auf der Tagesschau-Seite verfügbar ist. Nur wenn das der
Fall ist wird der Listenpunkt angezeigt. Warum das manchmal nicht der Fall
ist ist eines der Mysterien der Tagesschau-API.
Ich schaue mal am WE ob da was kaputt ist.

Viele Grüße
Christian
Am 22. Juli 2024 20:22:39 schrieb eusi ***@***.***>:

**Comment by eusi** [comment]
Mega! Dankeschön im Voraus!

**Comment by christianprasch** [comment]
Hallo eusi,

gerade getestet, Livestream ist verfügbar.
Kannst du mal bitte Feedback geben ob es nur ein temporäres Problem bei die war?

Viele Grüße
Christian

**Comment by eusi** [comment]
Hey @christianprasch , jetzt gerade zeigt es Livestream wieder an /cheers 
Denke damit ist das Ganze fürs Erste behoben ;-)
Danke dir!

**Comment by eusi** [comment]
Hey @christianprasch heute gab es bei den 20 Uhr Nachrichten leider wieder keinen Live-Stream Eintrag. Schon echt seltam ;-)
Ich schaue morgen Abend erneut ob es dann erscheint.
Kann es sein, dass es ggf. mehr als einen "Livestream" gibt und die ARD switched zwischen diesen?

**Comment by christianprasch** [comment]
Hallo eusi,

ich habe mal die Erkennung für die Verfügbarkeit eines Livestreams geändert. Ist nur mal auf Verdacht. Kannst du die neue Version mal hier auf Github ziehen und eine Zeit lang testen?
Wenn es damit besser geht mach ich einen PR an das Kodi-Team.

Viele Grüße
Christian

**Comment by eusi** [comment]
Hey Christian (@christianprasch ),
du hattest den richtigen Riecher!

Eben bei den 20 Uhr Nachrichten war bei der neuen App Version der Livestream vorhanden, während er bei der "Alten" gefehlt hat. D.h. dein Fix hat das Problem behoben 👍

**Comment by eusi** [comment]
Hey @christianprasch,
eben wollte ich noch scheiben, dass es durch die neue Verison behoben ist, aber es ist nun "anders" ^^

Ich benutze dein Plugin meist für die 20 Uhr Nachrichten. So auch heute. Testen tu ich in den letzten Tagen über 2 Kodis, einmal mit der offiziellen Version (2.5.7) und ein mal mit deiner neuen/gepatchten (2.5.8).

In den letzten Tagen war **dauerhaft** (also immer wenn ich untertags random nachgeschaut habe) der Livestream in der neuen Version (2.5.8) verfügbar.  👍
Heute war zu den 20 Uhr Nachrichten in der alten Version (2.5.7) der Livestream nicht sichtbar. 👎 

Bis hier hin sieht es aus, als würde die neue Version das Problem beheben. 🥇 

Problem war dann allerdings, dass heute um 20:13 plötzlich in der neuen Version (2.5.8) der Livestream in der Liste wieder verschwand, während ich den Tagesschau-Livestream noch schaute...

Kann man den Livestream-Eintrag nicht einfach permanent anzeigen? Ich meine der (ARD)Stream läuft doch vermutlich 24/7 (auch wenn es nicht immer die Tagesschau ist...)?

(Seitdem ein Kabelanschluss nicht mehr "Pflicht" ist, ist so ein Streams perfekt ;-)

Grüße,
Eusi

EDIT
Jetzt, 21:18 sehe ich wieder den Livestream bei beiden Versionen, oh man :o)

EDIT2
Ein Tag später, 08:00 (früh) auch interessant: Auf der alten Version (2.5.7) wird der Livestream in der Liste angezeigt, auf der neuen (2.5.8) nicht...

**Comment by christianprasch** [comment]
Hallo eusi,
ich geb jetzt auf da was parsen zu wollen.
Es gibt jetzt im Hauptmenü den Ordner "Livestreams", in dem werden alle Livestreams die die API anbietet aufgelistet.

Viele Grüße
Christian

**Comment by eusi** [comment]
Hey Christian,
sorry für die Umstände und danke für die Anpassungen. Ich werds testen, aber ich denke das ist nun die beste Alternative 👍 
eusi
