### ISSUE TITLE
„Nachrichten“ list stays empty while the other parts still show content

### ISSUE THREAD

**Issue by rfuh** [christianprasch/plugin.video.tagesschau#9]
In the Tagesschau AddOn, I do not see any videos anymore in the „Nachrichten“ topic. Other parts, like Livestream, „Tagesschau“ or „Tagesthemen“ still work though.
Asked this in kodinerds forum and they said there has been a change on ARD side which may need to be considered, see [forum](https://www.kodinerds.net/thread/79094-tagesschau-addon-keine-nachrichten-mehr/#post761155). Can you please check?
Thanks!!

**Comment by christianprasch** [comment]
Hello,
i am on holiday at the moment. I will have a look after 5.8.

**Comment by christianprasch** [comment]
Problem is fixed now.
Pull request to team Kodi is pending.
